const hashtags = {
  careerFa: [
    '#فرصت_شغلی',
    '#جویای_کار',
    '#استخدام',
    '#بازارکار',
    // '#بازار‌کار',
    '#بازار_کار',
    '#همکاری',
  ],
  careerEn: [
    '#job',
    '#job_oppurtinty',
    '#job_oppurtinty',
    '#employment',
  ],
  typeFa: [
    '#تمام_وقت',
    '#پاره_وقت',
    '#پروژه_ای',
    '#پروژه‌ای',
    '#دورکاری',
    '#دور‌کاری',
    '#فریلنسر',
    '#فریلنسری',
  ],
  typeEn: [
    '#remote',
    '#full_time',
    '#part_time',
    '#freelancer',
  ],
  positionFa: [
    '#طراح_سایت',
    '#طراح',
    '#برنامه_نویس',
    '#برنامه‌نویس',
    '#برنامه_نویس_موبایل',
    '#برنامه‌نویس_موبایل',
    '#طراح_UI',
    '#طراح_UX',
    '#دیزاینر',
    '#دولوپر',
    '#پروگرمر',
    '#دواپس',
    '#فرانت_اند',
    '#بک_اند',
    '#تستر',
    '#سیستم_ادمین',
    '#سیس_ادمین',
  ],
  positionEn: [
    '#web_developer',
    '#web_designer',
    '#designer',
    '#developer',
    '#programmer',
    '#coder',
    '#mobile_developer',
    '#ui_ux',
    '#ui_designer',
    '#ux_designer',
    '#front_end_developer',
    '#frontend_developer',
    '#back_end_developer',
    '#backend_developer',
    '#data_scientist',
    '#devops',
    '#dev_ops',
    '#tester',
    '#sysadmin',
    '#sys_admin',
    '#system_admin',
  ],
  levelFa: [
    '#جونیور',
    '#سنیور',
    '#کارآموز',
    '#کار‌آموز',
  ],
  levelEn: [
    '#junior',
    '#mid_level',
    '#senior',
    '#intern',
  ],
  technologiesFa: [
    /* Front-end */
    '#اچ‌_تی_ام_ال',
    // '#اچ‌‌تی‌ام‌ال',
    '#سی‌_اس_اس',
    '#بوت_استرپ',
    '#جی_کوئری',
    '#جی_اس',
    '#جاوااسکریپت',
    '#جاوا‌اسکریپت',
    '#جاوا_اسکریپت',
    // '#ویو',
    '#ویو_جی_اس',
    '#ری‌اکت',
    '#ری_اکت‌',
    '#انگولار',
    '#انگولار_جی_ای',

    /* Back-end */
    // '#نود',
    '#نود_جی_اس',
    '#اکسپرس',
    '#اکسپرس_جی_اس',
    '#جاوا',
    '#اسپرینگ',
    '#روبی',
    '#پایتون',
    '#جنگو',
    '#پی_اچ_پی',
    '#لاراول',
    '#لومن',

    /* Database */
    '#دیتابیس',
    '#مونگو',

    /* Mobile */
    '#اندروید',
    '#فلاتر',
    '#کاتلین',
    '#ری_اکت_نیتیو',
    '#ری‌اکت_نیتیو',
    '#سوییفت',
    '#سوئیفت',

    /* Other */
    // '#سی',
    '#سی_شارپ',
    '#دات_نت',
    '#سی_پلاس_پلاس',
    '#سی_پ_پ',
    // '#اسکالا',
    // '#ایدا',
    // '#لیسپ',
    // '#پرولوگ',

    /* CMS */
    '#وردپرس',
    '#جوملا',

    /* Sys. Admin & DevOps */
    // '#الپیک',
    '#لینوکس',
    // '#سرور',
    '#اوبونتو',
    '#سلنیوم',
  ],
  technologiesEn: [
    /* Front-end */
    '#html',
    '#css',
    '#bootstrap',
    '#jquery',
    '#js',
    '#javascript',
    // '#java_script',
    '#sass',
    '#vue',
    '#vuejs',
    '#vue_js',
    '#react',
    '#reactjs',
    '#react_js',
    '#angular',
    '#angularjs',
    '#angular_js',

    /* Back-end */
    '#node',
    '#nodejs',
    '#node_js',
    '#express',
    '#expressjs',
    '#express_js',
    '#java',
    '#spring',
    '#ruby',
    '#rails',
    '#python',
    '#django',
    '#php',
    '#lumen',
    '#laravel',

    /* Database */
    '#db',
    '#mysql',
    '#my_sql',
    '#mssql',
    '#ms_sql',
    '#mongo',
    '#mongodb',
    '#mongo_db',

    /* Mobile */
    '#android',
    '#flutter',
    '#kotlin',
    '#react_native',
    '#swift',
    '#objective_c',

    /* Other */
    // '#c',
    // '#csharp',
    '#c_sharp',
    '#dotnet',
    '#cplusplus',
    '#c_plus_plus',
    // '#scala',
    // '#r',
    // '#ada',
    // '#lisp',
    // '#prolog',

    /* CMS */
    // '#word_press',
    '#wordpress',
    '#joomla',

    /* Sys. Admin & DevOps */
    '#lpic',
    '#linux',
    '#server',
    '#ubuntu',
    '#selenium',
  ],
  KarJoorFa: [
    '#کارجور',
    '#کار_جور',
    'کارجور',
    'کار جور',
  ],
  KarJoorEn: [
    '#karjoor',
    '#kar_joor',
    'karjoor',
  ],
  otherFa: [
    '#جاباینجا',
    '#جاب_اینجا',
  ],
  otherEn: [
    '#job_inja',
    '#jobinja',
  ],
};

module.exports = hashtags;
